name: b2b_services
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_maps_flutter: ^2.2.1
  dotted_line: ^3.1.0
  geolocator: ^9.0.2
  qr_code_scanner: ^1.0.1
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  sizer: ^2.0.15
  flutter_switch: ^0.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

